# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18e69768061efb4d30d01c916a58efdc529bee46bb14e11ad88f90e093878e88d27636b48ef2553eff8f9eb238525f678cb6a5f3c7ac9ce196036d062f25a2ca

test:
  secret_key_base: 996a9a7b7e1f63e192e2e1a1b1a061d2c4d773ded1aa58410cc054e949d35cce8573356d648cd86c488ed31628f59e202058644811e480964e09f3581dbf228f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
